use PROYECTO_CSHARP

CREATE PROC SP_LISTAR_EMPLEADOS
AS 
BEGIN
SELECT        E.EMPLEADO_ID, E.APELLIDOS, E.NOMBRE, E.DNI, E.GENERO, D.NOMBRE_DISTRITO
FROM            EMPLEADOS AS E INNER JOIN
                         DISTRITOS AS D ON D.DISTRITO_ID = D.DISTRITO_ID
END

EXEC SP_LISTAR_EMPLEADOS




SELECT * FROM EMPLEADOS

INSERT INTO EMPLEADOS(APELLIDOS,NOMBRE,DNI,GENERO,ESTADO_CIVIL,DIRECCION,DISTRITO_ID) VALUES(
'DIAZ',
'EDWARD',
'12',
'MASCULINO',
'CASADO',
'CALLE 36',
'1'
)

CREATE PROC SP_REGISTRAR_EMPLEADO
@APELLIDOS VARCHAR(100),
@NOMBRE VARCHAR(60),
@DNI VARCHAR(5) ,
@GENERO VARCHAR(30) ,
@ESTADO_CIVIL VARCHAR(30),
@DIRECCION VARCHAR(300),
@DISTRITO_ID VARCHAR(7),
@ULTIMO_ID INT OUTPUT
AS
BEGIN
INSERT INTO EMPLEADOS
                         (APELLIDOS, NOMBRE, DNI, GENERO, ESTADO_CIVIL, DIRECCION, DISTRITO_ID)
VALUES        (@APELLIDOS,@NOMBRE,@DNI,@GENERO,@ESTADO_CIVIL,@DIRECCION,@DISTRITO_ID)
SET @ULTIMO_ID =SCOPE_IDENTITY()
RETURN @ULTIMO_ID
END

DROP PROC SP_REGISTRAR_EMPLEADO