use PROYECTO_CSHARP

CREATE PROC SP_LISTAR_EMPLEADOS
AS 
BEGIN
SELECT        E.EMPLEADO_ID, E.APELLIDOS, E.NOMBRE, E.DNI, E.GENERO, D.NOMBRE_DISTRITO
FROM            EMPLEADOS AS E INNER JOIN
                         DISTRITOS AS D ON D.DISTRITO_ID = D.DISTRITO_ID
END

EXEC SP_LISTAR_EMPLEADOS