
CREATE PROC SP_LISTAR_DEPARTAMENTOS
AS 
BEGIN
	SELECT * FROM DEPARTAMENTOS
END

SELECT * FROM PROVINCIAS

CREATE PROC SP_LISTAR_PROVINCIAS
@DEPARTAMENTO_ID VARCHAR(7)
AS 
BEGIN
	SELECT * FROM PROVINCIAS WHERE DEPARTAMENTO_ID = @DEPARTAMENTO_ID
END

SELECT * FROM DISTRITOS

CREATE PROC SP_LISTAR_DISTRITOS
@PROVINCIA_ID VARCHAR(7)
AS
BEGIN
 SELECT * FROM DISTRITOS WHERE PROVINCIA_ID = @PROVINCIA_ID
END

INSERT INTO DISTRITOS VALUES (5,'distrito',141)

EXEC SP_LISTAR_DEPARTAMENTOS