USE PROYECTO_CSHARP


CREATE PROC PS_BUSCAR_EMPLEADO_LIKE
@NOMBRE VARCHAR(60)
AS
BEGIN
SELECT 
	EMPLEADO_ID,
	APELLIDOS,
	NOMBRE,
	DNI,
	GENERO,
	NOMBRE_DISTRITO
FROM EMPLEADOS E
INNER JOIN 
	DISTRITOS D ON E.DISTRITO_ID = D.DISTRITO_ID
WHERE 
	NOMBRE LIKE '%'+@NOMBRE+'%'
END

EXEC PS_BUSCAR_EMPLEADO_LIKE 'F'