use PROYECTO_CSHARP

SELECT * FROM EMPLEADOS


--registrar telefonos

CREATE PROC SP_REGISTAR_TELEFONOS
@OPERADOR VARCHAR(50),
@NUMERO VARCHAR(10),
@EMPLEADO_ID VARCHAR(7)
AS
BEGIN
INSERT INTO TELEFONOS
                         (OPERADOR, NUMERO, EMPLEADO_ID)
VALUES        (@OPERADOR,@NUMERO,@EMPLEADO_ID)
END


DROP PROC SP_REGISTAR_TELEFONOS
select * from telefonos

SELECT * FROM DISTRITOS

EXEC SP_REGISTRAR_EMPLEADO

ALTER TABLE telefonos ALTER COLUMN NUMERO VARCHAR(20);

SELECT * FROM EMPLEADOS

SELECT COUNT(DNI) FROM EMPLEADOS WHERE DNI='12G'

CREATE PROC PS_BUSCAR_DNI
@DNI CHAR(8)
AS
BEGIN
END